# Generated by Django 2.2.12 on 2020-08-10 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blackcloverApp', '0004_auto_20200809_0650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='contact',
        ),
    ]
